name: Publish package to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: yarn
      - run: yarn build
      - run: yarn publish --access=public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
